[package]
name = "mimic-app"
version = "1.0.0"
description = "Mimic Link VPN"
authors = ["you"]
edition = "2021"

# Instrucciones de construcción
[build-dependencies]
tauri-build = { version = "2.0", features = [] }

# Librerías (Ingredientes)
[dependencies]
tauri = { version = "2.0", features = [] }
tauri-plugin-opener = "2.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# VPN Driver
wintun = "0.5.0"

# UPnP (Botón Abrir Puertos)
igd-next = "0.14.3"

# Nube Steam (Render)
tungstenite = { version = "0.20", features = ["rustls-tls-native-roots"] }
url = "2.5"

# Criptografía "Militar" (La misma que usa Google y WireGuard)
chacha20poly1305 = "0.10"
rand = "0.8"
base64 = "0.21"
