[package]
name = "mimic-app"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "mimic_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
igd-next = "0.14.3"
tungstenite = { version = "0.20", features = ["rustls-tls-native-roots"] }
url = "2.5"
serde_json = "1.0"

# Para manejar la tarjeta de red virtual
wintun = "0.5.0" 
# Para funciones Ãºtiles de sistema
libloading = "0.8"
# Para generar IPs aleatorias si hace falta
rand = "0.8"
