[package]
name = "mimic-app"
version = "1.0.0"
description = "Mimic Link VPN"
authors = ["you"]
edition = "2021"

# Instrucciones de construcción
[build-dependencies]
tauri-build = { version = "2.0", features = [] }

# Librerías (Ingredientes de alto rendimiento)
[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# --- MOTOR DE RED (Driver VPN) ---
wintun = "0.4"

# --- SEGURIDAD (Criptografía de Grado Militar) ---
chacha20poly1305 = "0.10"
rand = "0.8"
base64 = "0.21"

# --- VELOCIDAD (Compresión LZ4) ---
lz4_flex = "0.11"

# --- CONECTIVIDAD (Apertura Automática de Puertos UPnP) ---
igd-next = "0.14"
