[package]
name = "mimic-app"
version = "1.0.0"
description = "Mimic Link VPN"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0", features = [] }

[dependencies]
# --- CAMBIO IMPORTANTE AQUÍ ABAJO ---
# Activamos "tray-icon" (Bandeja) y "image-png" (Iconos) para el Modo Fantasma
tauri = { version = "2", features = ["tray-icon", "image-png"] }

tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

# RED Y VPN
wintun = "0.4"
igd-next = "0.14"

# SEGURIDAD Y COMPRESIÓN
chacha20poly1305 = "0.10"
rand = "0.8"
base64 = "0.21"
lz4_flex = "0.11"
x25519-dalek = { version = "2.0", features = ["static_secrets", "getrandom"] }

# ARCHIVOS
rfd = "0.14"
dirs = "5.0"
